"""add sandbox runtime models

Revision ID: 05e50a9c2909
Revises: 01193aa32b83
Create Date: 2026-02-14 04:26:05.973358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05e50a9c2909'
down_revision: Union[str, None] = '01193aa32b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sandboxes',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('resource_limits', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('network_policy', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('environment', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandboxes_agent_id'), 'sandboxes', ['agent_id'], unique=False)
    op.create_index(op.f('ix_sandboxes_org_id'), 'sandboxes', ['org_id'], unique=False)
    op.create_index('ix_sandboxes_org_id_agent_id', 'sandboxes', ['org_id', 'agent_id'], unique=False)
    op.create_index('ix_sandboxes_org_id_status', 'sandboxes', ['org_id', 'status'], unique=False)
    op.create_table('sandbox_executions',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('sandbox_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('resource_usage', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_executions_org_id'), 'sandbox_executions', ['org_id'], unique=False)
    op.create_index('ix_sandbox_executions_org_id_status', 'sandbox_executions', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_sandbox_executions_sandbox_id'), 'sandbox_executions', ['sandbox_id'], unique=False)
    op.create_index('ix_sandbox_executions_sandbox_id_status', 'sandbox_executions', ['sandbox_id', 'status'], unique=False)
    op.create_table('sandbox_audit_logs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action_detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('capability_matched', sa.String(length=255), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['sandbox_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_audit_logs_execution_id'), 'sandbox_audit_logs', ['execution_id'], unique=False)
    op.create_index('ix_sandbox_audit_logs_execution_id_ts', 'sandbox_audit_logs', ['execution_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sandbox_audit_logs_org_id'), 'sandbox_audit_logs', ['org_id'], unique=False)
    op.create_index('ix_sandbox_audit_logs_org_id_action_type', 'sandbox_audit_logs', ['org_id', 'action_type'], unique=False)
    op.drop_index('ix_shadow_ai_org_id', table_name='shadow_ai_discoveries')
    op.create_index(op.f('ix_shadow_ai_discoveries_org_id'), 'shadow_ai_discoveries', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shadow_ai_discoveries_org_id'), table_name='shadow_ai_discoveries')
    op.create_index('ix_shadow_ai_org_id', 'shadow_ai_discoveries', ['org_id'], unique=False)
    op.drop_index('ix_sandbox_audit_logs_org_id_action_type', table_name='sandbox_audit_logs')
    op.drop_index(op.f('ix_sandbox_audit_logs_org_id'), table_name='sandbox_audit_logs')
    op.drop_index('ix_sandbox_audit_logs_execution_id_ts', table_name='sandbox_audit_logs')
    op.drop_index(op.f('ix_sandbox_audit_logs_execution_id'), table_name='sandbox_audit_logs')
    op.drop_table('sandbox_audit_logs')
    op.drop_index('ix_sandbox_executions_sandbox_id_status', table_name='sandbox_executions')
    op.drop_index(op.f('ix_sandbox_executions_sandbox_id'), table_name='sandbox_executions')
    op.drop_index('ix_sandbox_executions_org_id_status', table_name='sandbox_executions')
    op.drop_index(op.f('ix_sandbox_executions_org_id'), table_name='sandbox_executions')
    op.drop_table('sandbox_executions')
    op.drop_index('ix_sandboxes_org_id_status', table_name='sandboxes')
    op.drop_index('ix_sandboxes_org_id_agent_id', table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_org_id'), table_name='sandboxes')
    op.drop_index(op.f('ix_sandboxes_agent_id'), table_name='sandboxes')
    op.drop_table('sandboxes')
    # ### end Alembic commands ###
