"""initial_models

Revision ID: 3c01282347e9
Revises: 
Create Date: 2026-02-06 23:20:52.063033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c01282347e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan_tier', sa.String(length=50), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('alert_destinations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('destination_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_destinations_org_id'), 'alert_destinations', ['org_id'], unique=False)
    op.create_index('ix_alert_destinations_org_id_is_active', 'alert_destinations', ['org_id', 'is_active'], unique=False)
    op.create_table('api_keys',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default='["proxy"]', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_index('ix_api_keys_org_id_is_active', 'api_keys', ['org_id', 'is_active'], unique=False)
    op.create_index('ix_api_keys_prefix', 'api_keys', ['prefix'], unique=False)
    op.create_table('detectors',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('action_mode', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detectors_org_id'), 'detectors', ['org_id'], unique=False)
    op.create_index('ix_detectors_org_id_category', 'detectors', ['org_id', 'category'], unique=False)
    op.create_index('ix_detectors_org_id_is_active', 'detectors', ['org_id', 'is_active'], unique=False)
    op.create_table('proxy_endpoints',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_endpoints_org_id'), 'proxy_endpoints', ['org_id'], unique=False)
    op.create_index('ix_proxy_endpoints_org_id_is_active', 'proxy_endpoints', ['org_id', 'is_active'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index('ix_users_org_id_email', 'users', ['org_id', 'email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_index('ix_audit_logs_org_id_action', 'audit_logs', ['org_id', 'action'], unique=False)
    op.create_index('ix_audit_logs_org_id_created_at', 'audit_logs', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_org_id_resource_type', 'audit_logs', ['org_id', 'resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('detector_rules',
    sa.Column('detector_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['detectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detector_rules_detector_id'), 'detector_rules', ['detector_id'], unique=False)
    op.create_table('proxy_requests',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['proxy_endpoints.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_requests_endpoint_id'), 'proxy_requests', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_proxy_requests_org_id'), 'proxy_requests', ['org_id'], unique=False)
    op.create_index('ix_proxy_requests_org_id_created_at', 'proxy_requests', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_proxy_requests_org_id_endpoint_id', 'proxy_requests', ['org_id', 'endpoint_id'], unique=False)
    op.create_index('ix_proxy_requests_org_id_model', 'proxy_requests', ['org_id', 'model'], unique=False)
    op.create_table('incidents',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('proxy_request_id', sa.UUID(), nullable=True),
    sa.Column('detector_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['detectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proxy_request_id'], ['proxy_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_detector_id'), 'incidents', ['detector_id'], unique=False)
    op.create_index(op.f('ix_incidents_org_id'), 'incidents', ['org_id'], unique=False)
    op.create_index('ix_incidents_org_id_category', 'incidents', ['org_id', 'category'], unique=False)
    op.create_index('ix_incidents_org_id_created_at', 'incidents', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_incidents_org_id_severity', 'incidents', ['org_id', 'severity'], unique=False)
    op.create_index('ix_incidents_org_id_status', 'incidents', ['org_id', 'status'], unique=False)
    op.create_index(op.f('ix_incidents_proxy_request_id'), 'incidents', ['proxy_request_id'], unique=False)
    op.create_table('alerts',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['alert_destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_destination_id'), 'alerts', ['destination_id'], unique=False)
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_index('ix_alerts_incident_id_status', 'alerts', ['incident_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_org_id'), 'alerts', ['org_id'], unique=False)
    op.create_index('ix_alerts_org_id_status', 'alerts', ['org_id', 'status'], unique=False)
    op.create_table('incident_actions',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_actions_incident_id'), 'incident_actions', ['incident_id'], unique=False)
    op.create_index('ix_incident_actions_incident_id_created_at', 'incident_actions', ['incident_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_incident_actions_user_id'), 'incident_actions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_actions_user_id'), table_name='incident_actions')
    op.drop_index('ix_incident_actions_incident_id_created_at', table_name='incident_actions')
    op.drop_index(op.f('ix_incident_actions_incident_id'), table_name='incident_actions')
    op.drop_table('incident_actions')
    op.drop_index('ix_alerts_org_id_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_org_id'), table_name='alerts')
    op.drop_index('ix_alerts_incident_id_status', table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_destination_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_incidents_proxy_request_id'), table_name='incidents')
    op.drop_index('ix_incidents_org_id_status', table_name='incidents')
    op.drop_index('ix_incidents_org_id_severity', table_name='incidents')
    op.drop_index('ix_incidents_org_id_created_at', table_name='incidents')
    op.drop_index('ix_incidents_org_id_category', table_name='incidents')
    op.drop_index(op.f('ix_incidents_org_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_detector_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_proxy_requests_org_id_model', table_name='proxy_requests')
    op.drop_index('ix_proxy_requests_org_id_endpoint_id', table_name='proxy_requests')
    op.drop_index('ix_proxy_requests_org_id_created_at', table_name='proxy_requests')
    op.drop_index(op.f('ix_proxy_requests_org_id'), table_name='proxy_requests')
    op.drop_index(op.f('ix_proxy_requests_endpoint_id'), table_name='proxy_requests')
    op.drop_table('proxy_requests')
    op.drop_index(op.f('ix_detector_rules_detector_id'), table_name='detector_rules')
    op.drop_table('detector_rules')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_id_resource_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_id_action', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_org_id_email', table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_proxy_endpoints_org_id_is_active', table_name='proxy_endpoints')
    op.drop_index(op.f('ix_proxy_endpoints_org_id'), table_name='proxy_endpoints')
    op.drop_table('proxy_endpoints')
    op.drop_index('ix_detectors_org_id_is_active', table_name='detectors')
    op.drop_index('ix_detectors_org_id_category', table_name='detectors')
    op.drop_index(op.f('ix_detectors_org_id'), table_name='detectors')
    op.drop_table('detectors')
    op.drop_index('ix_api_keys_prefix', table_name='api_keys')
    op.drop_index('ix_api_keys_org_id_is_active', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_alert_destinations_org_id_is_active', table_name='alert_destinations')
    op.drop_index(op.f('ix_alert_destinations_org_id'), table_name='alert_destinations')
    op.drop_table('alert_destinations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
