"""add sandbox_execution_id to proxy_requests and incidents

Revision ID: 8822459aa6a2
Revises: 05e50a9c2909
Create Date: 2026-02-14 00:04:11.229721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8822459aa6a2'
down_revision: Union[str, None] = '05e50a9c2909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('sandbox_execution_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_incidents_sandbox_execution_id'), 'incidents', ['sandbox_execution_id'], unique=False)
    op.create_foreign_key(None, 'incidents', 'sandbox_executions', ['sandbox_execution_id'], ['id'], ondelete='SET NULL')
    op.add_column('proxy_requests', sa.Column('sandbox_execution_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_proxy_requests_sandbox_execution_id'), 'proxy_requests', ['sandbox_execution_id'], unique=False)
    op.create_foreign_key(None, 'proxy_requests', 'sandbox_executions', ['sandbox_execution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proxy_requests', type_='foreignkey')
    op.drop_index(op.f('ix_proxy_requests_sandbox_execution_id'), table_name='proxy_requests')
    op.drop_column('proxy_requests', 'sandbox_execution_id')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_index(op.f('ix_incidents_sandbox_execution_id'), table_name='incidents')
    op.drop_column('incidents', 'sandbox_execution_id')
    # ### end Alembic commands ###
