"""add_sso_config_and_user_sso_fields

Revision ID: 9204376b97eb
Revises: eaf7adc024f9
Create Date: 2026-02-07 14:10:10.494430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9204376b97eb'
down_revision: Union[str, None] = 'eaf7adc024f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_configs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('saml_entity_id', sa.String(length=500), nullable=True),
    sa.Column('saml_sso_url', sa.String(length=500), nullable=True),
    sa.Column('saml_x509_cert', sa.Text(), nullable=True),
    sa.Column('saml_metadata_xml', sa.Text(), nullable=True),
    sa.Column('oidc_issuer', sa.String(length=500), nullable=True),
    sa.Column('oidc_client_id', sa.String(length=255), nullable=True),
    sa.Column('oidc_client_secret', sa.String(length=255), nullable=True),
    sa.Column('oidc_discovery_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sso_configs_org_id'), 'sso_configs', ['org_id'], unique=False)
    op.create_index('ix_sso_configs_org_provider', 'sso_configs', ['org_id', 'provider_type'], unique=False)
    op.add_column('users', sa.Column('sso_provider', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('sso_external_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('ix_users_sso_lookup', 'users', ['sso_provider', 'sso_external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_sso_lookup', table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'sso_external_id')
    op.drop_column('users', 'sso_provider')
    op.drop_index('ix_sso_configs_org_provider', table_name='sso_configs')
    op.drop_index(op.f('ix_sso_configs_org_id'), table_name='sso_configs')
    op.drop_table('sso_configs')
    # ### end Alembic commands ###
