"""add retention policy and data archive

Revision ID: a53e5e46e529
Revises: fa1414a3d1a9
Create Date: 2026-02-07 15:12:52.803081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53e5e46e529'
down_revision: Union[str, None] = 'fa1414a3d1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_archives',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_archives_org_dates', 'data_archives', ['org_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_data_archives_org_id'), 'data_archives', ['org_id'], unique=False)
    op.create_index('ix_data_archives_org_table', 'data_archives', ['org_id', 'table_name'], unique=False)
    op.create_table('retention_policies',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('proxy_requests_days', sa.Integer(), nullable=False),
    sa.Column('incidents_days', sa.Integer(), nullable=False),
    sa.Column('audit_logs_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_policies_org_id'), 'retention_policies', ['org_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_policies_org_id'), table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index('ix_data_archives_org_table', table_name='data_archives')
    op.drop_index(op.f('ix_data_archives_org_id'), table_name='data_archives')
    op.drop_index('ix_data_archives_org_dates', table_name='data_archives')
    op.drop_table('data_archives')
    # ### end Alembic commands ###
